application: hosted-caravel
runtime: python27
api_version: 1
version: 1
threadsafe: yes

handlers:
- url: /_internal.*
  script: caravel.app
  login: admin
- url: /static
  static_dir: caravel/static
  secure: always
- url: /moderation.*
  script: caravel.app
  login: admin
  secure: always
- url: /oshalogin.*
  script: caravel.app
  login: required
  secure: always
- url: /api/v1/.*
  script: caravel.app
  login: required
  secure: always
- url: /.*
  script: caravel.app
  secure: always

builtins:
- deferred: on
- remote_api: on

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^.*venv.*$

default_expiration: "2d"

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: "15s"
  max_pending_latency: "15s"

