application: hosted-caravel
runtime: python27
api_version: 1
version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: caravel/static
  secure: always
- url: /moderation.*
  script: caravel.app
  login: admin
  secure: always
- url: /_internal/.*
  script: caravel.app
  login: admin
  secure: always
- url: /login.*
  script: caravel.app
  login: required
  secure: always
- url: /.*
  script: caravel.app
  secure: always

builtins:
- deferred: on
- remote_api: on

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^.*venv.*$
